export const CONSTANT = {
  CREATE_NETWORK: "创建网络",
  DELETE_NETWORK: "删除网络",
  UPDATE_NETWORK: "更新网络",
  PARENT: "所属上级",
  START_IP_ADDRESS: "开始地址",
  END_IP_ADDRESS: "结束地址",
  NETMASK: "子网掩码",
  GATEWAY: "网关",
  VLAN: "vlan",
  REMARK: "备注",
  SUBMIT: "提交",
  COMFIRM: "确认",
  NETWORK_NAME: "网络名称",
  CREATE: "新增",
  DELETE: "删除",
  UPDATE: "修改",
  SEARCH: "搜索",
  FIND: "查找",
};
